name:        git-events
version:     0.1.0
# The vendor for the snap (replace 'Vendor <email@example.com>')
vendor:      Vendor <email@example.com>
summary:     Cross-language git hook event-emitter.
description: # A longer description for the snap
icon: # A path to an icon for the package
parts:
  listener: